apiVersion: v1
kind: ConfigMap
metadata:
  name: contributor-agreement-app-cm
data:
  artifactName: repo-abpmn-poc.tar.gz
  artifactSha256: "change something eb9c2cf53f526f2692c428fc4fd"
  # command sha256sum bpmn-poc.tar.gz
  artifactUrl: "abcd.efgh"
