apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: camunda-deployer
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: camunda-dev
    #      - env: qa
    #        namespace: camunda-qa
    #      - env: prod
    #        namespace: camunda-prod
  template:
    metadata:
      name: "camunda-jobs-{{env}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/org/ARGOCD-JOBS
        targetRevision: HEAD
        path: "jobs/{{env}}"          # ArgoCD auto detects kustomization.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true