apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: contributor-agreement-app-cm
    behavior: merge
    literals:
      - artifactUrl="https://repo-b-changed-11111dev-artifact-url/file.bpmn"
      - environment="qa"