apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: camunda-bpmn-artifact-repo-a
    behavior: merge
    literals:
      - artifactUrl="https://repo-a-changed-11111dev-artifact-url/file.bpmn"
      - environment="qa"