apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kustomize-new-qa
resources:
  - ../base/contributor-agreement-app
  - ../base/violations-management-app
patches:
 - path: configmap-patch-violations-cm.yaml
 - path: configmap-patch-contributors-cm.yaml

