apiVersion: v1
kind: ConfigMap
metadata:
  name: violations-management-app-cm
data:
  artifactName: repo-b-bpmn-poc.tar.gz
  artifactSha256: "281b003284e8145b611f02ac4c141736e8ffeeb9c2cf53f526f2692c428fc4fd"
  # command sha256sum bpmn-poc.tar.gz
  artifactUrl: "abcd.efgh"