apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: violations-management-app-cm
    behavior: merge
    literals:
      - artifactUrl="https://violations-app-changed-11111dev-artifact-url/file.bpmn"
      - environment="dev"
