apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kustomize-new-dev
resources:
  - ../base/contributor-agreement-app
  - ../base/violations-management-app
patches:
  - path: configmap-patch-contributors-cm.yaml
  - path: configmap-patch-violations-cm.yaml
  

